var searchData=
[
  ['random',['Random',['../group__Core.html#classcrpropa_1_1Random',1,'crpropa']]],
  ['redshift',['Redshift',['../group__EnergyLosses.html#classcrpropa_1_1Redshift',1,'crpropa']]],
  ['ref_5fptr',['ref_ptr',['../group__Core.html#classcrpropa_1_1ref__ptr',1,'crpropa']]],
  ['ref_5fptr_3c_20candidate_20_3e',['ref_ptr&lt; Candidate &gt;',['../group__Core.html',1,'crpropa']]],
  ['ref_5fptr_3c_20crpropa_3a_3aadvectionfield_20_3e',['ref_ptr&lt; crpropa::AdvectionField &gt;',['../group__Core.html',1,'crpropa']]],
  ['ref_5fptr_3c_20crpropa_3a_3acandidate_20_3e',['ref_ptr&lt; crpropa::Candidate &gt;',['../group__Core.html',1,'crpropa']]],
  ['ref_5fptr_3c_20crpropa_3a_3acrpropa_3a_3amagneticfield_20_3e',['ref_ptr&lt; crpropa::crpropa::MagneticField &gt;',['../group__Core.html',1,'crpropa']]],
  ['ref_5fptr_3c_20crpropa_3a_3adensity_20_3e',['ref_ptr&lt; crpropa::Density &gt;',['../group__Core.html',1,'crpropa']]],
  ['ref_5fptr_3c_20crpropa_3a_3aemissionmap_20_3e',['ref_ptr&lt; crpropa::EmissionMap &gt;',['../group__Core.html',1,'crpropa']]],
  ['ref_5fptr_3c_20crpropa_3a_3agrid_20_3e',['ref_ptr&lt; crpropa::Grid &gt;',['../group__Core.html',1,'crpropa']]],
  ['ref_5fptr_3c_20crpropa_3a_3amagneticfield_20_3e',['ref_ptr&lt; crpropa::MagneticField &gt;',['../group__Core.html',1,'crpropa']]],
  ['ref_5fptr_3c_20crpropa_3a_3amodule_20_3e',['ref_ptr&lt; crpropa::Module &gt;',['../group__Core.html',1,'crpropa']]],
  ['ref_5fptr_3c_20crpropa_3a_3amodulelist_20_3e',['ref_ptr&lt; crpropa::ModuleList &gt;',['../group__Core.html',1,'crpropa']]],
  ['ref_5fptr_3c_20crpropa_3a_3aobserverfeature_20_3e',['ref_ptr&lt; crpropa::ObserverFeature &gt;',['../group__Core.html',1,'crpropa']]],
  ['ref_5fptr_3c_20crpropa_3a_3asource_20_3e',['ref_ptr&lt; crpropa::Source &gt;',['../group__Core.html',1,'crpropa']]],
  ['ref_5fptr_3c_20crpropa_3a_3asourcefeature_20_3e',['ref_ptr&lt; crpropa::SourceFeature &gt;',['../group__Core.html',1,'crpropa']]],
  ['ref_5fptr_3c_20crpropa_3a_3asurface_20_3e',['ref_ptr&lt; crpropa::Surface &gt;',['../group__Core.html',1,'crpropa']]],
  ['ref_5fptr_3c_20cylindricalprojectionmap_20_3e',['ref_ptr&lt; CylindricalProjectionMap &gt;',['../group__Core.html',1,'crpropa']]],
  ['ref_5fptr_3c_20module_20_3e',['ref_ptr&lt; Module &gt;',['../group__Core.html',1,'crpropa']]],
  ['referenced',['Referenced',['../group__Core.html#classcrpropa_1_1Referenced',1,'crpropa']]],
  ['reflectivebox',['ReflectiveBox',['../group__Condition.html#classcrpropa_1_1ReflectiveBox',1,'crpropa']]],
  ['renormalizemagneticfield',['RenormalizeMagneticField',['../group__MagneticFields.html#classcrpropa_1_1RenormalizeMagneticField',1,'crpropa']]],
  ['restricttoregion',['RestrictToRegion',['../group__Condition.html#classcrpropa_1_1RestrictToRegion',1,'crpropa']]]
];
